config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :forums
  resources :galleries
  devise_for :users
  get 'static_pages/homepage'

  get 'static_pages/dashboard'
  get 'static_pages/uc'

  resources :clubs do
    get '/clubs/:id', to: 'clubs#show'
  end
  resources :products
  resources :events

    root 'static_pages#uc'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def homepage
  end

  def dashboard
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_login_modal.html.erb
<div class="modal hide fade in" id="login">

<div class="modal-header">

<button class="close" data-dismiss="modal">x</button>

<h2>Sign in</h2>

</div>

<div class="modal-body">

<%= simple_form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>

<div><%= f.label :email %><br />

<%= f.email_field :email, :autofocus => true %></div>

<div><%= f.label :password %><br />

<%= f.password_field :password %></div>

<% if devise_mapping.rememberable? -%>

<div><%= f.check_box :remember_me %> <%= f.label :remember_me %></div>

<% end -%>
<%= f.submit "Sign in", :class => 'btn btn-small btn-success' %>

<% end %>

</div>

<div class="modal-footer">

<%= render "devise/shared/links" %>

</div>

</div>

app/views/static_pages/_sign_up_modal.html.erb
<div class="modal hide fade in" id="sign_up">

<div class="modal-header">

<button class="close" data-dismiss="modal">x</button>

<h2>Sign Up</h2>

</div>

<div class="modal-body">

<%= simple_form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>

<%= devise_error_messages! %>

<div><%= f.label :email %><br />

<%= f.email_field :email, :autofocus => true %></div>

<div><%= f.label :password %><br />

<%= f.password_field :password %></div>

<div><%= f.label :password_confirmation %><br />

<%= f.password_field :password_confirmation %></div>

</div>

<div class="modal-footer">

<p><div><%= f.submit "Sign up", :class => 'btn btn-small btn-success' %></div></p>

<p><a href="#" class="btn btn-small" data-dismiss="modal">Close</a></p>

</div>

<% end %>

</div>

app/views/static_pages/dashboard.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Xeon | OnePage Responsive Theme</title>
    <link href="/assets/bootstrap.min.css" rel="stylesheet">
    <link href="/assets/font-awesome.min.css" rel="stylesheet">
    <link href="/assets/prettyPhoto.css" rel="stylesheet">
    <link href="/assets/main.css" rel="stylesheet">
    <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    <![endif]-->
    <link rel="shortcut icon" href="/assets/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/assets/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/assets/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/assets/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="/assets/apple-touch-icon-57-precomposed.png">
</head><!--/head-->

<section id="services">
        <div class="container">
            <div class="box first">
                <div class="center">
                <h1>Welcome, Fighter</h1>
            </div>
                <div class="row">
                    <div class="col-md-4 col-sm-6">
                        <div class="center">
                            <i class="icon-home icon-md icon-color1"></i>
                            <a href="/clubs"><h4>Clubs</h4></a>
                            <p>Check out all the Clubs, Gyms & Training center near you. Chosse And compare beetween the best Clubs & and gyms, see prices, ratings & services.</p>
                        </div>
                    </div><!--/.col-md-4-->
                    <div class="col-md-4 col-sm-6">
                        <div class="center">
                            <i class="icon-calendar icon-md icon-color2"></i>
                            <a href="/events"><h4>Events</h4></a>
                            <p>Check out the upcoming events in town, join in and tell people that you are supporting the event by sharing it on Social Sites. </p>
                        </div>
                    </div><!--/.col-md-4-->
                    <div class="col-md-4 col-sm-6">
                        <div class="center">
                            <i class="icon-shopping-cart icon-md icon-color3"></i>
                            <a href="/products"><h4>Store</h4></a>
                            <p>Be a real fighter, check out all the Taponomics goddies, choose a product and order it for yourself and your loved ones just by calling us.</p>
                        </div>
                    </div><!--/.col-md-4-->
                    <div class="col-md-4 col-sm-6">
                        <div class="center">
                            <i class="icon-comment icon-md icon-color4"></i>
                            <a href="/forums"><h4>Forum</h4></a>
                            <p>Feeling low, facing problems, don't know whome to share with? Speak it up tell us about it we promise will help and also to keep secrets.</p>
                        </div>
                    </div><!--/.col-md-4-->
                    <div class="col-md-4 col-sm-6">
                        <div class="center">
                            <i class="icon-picture icon-md icon-color5"></i>
                            <a href="/galleries"><h4>Gallery</h4></a>
                            <p>Wanna get inspired! Watch our fights and and have a look at our awesome pictures of evnts, fights, and gyms.</p>
                        </div>
                    </div><!--/.col-md-4-->
                    <div class="col-md-4 col-sm-6">
                        <div class="center">
                            <i class="icon-user icon-md icon-color6"></i>
                            <a href="/users/edit"><h4>My Account</h4></a>
                            <p>Wanna add something new to your profile, or just wanna change your credentials, just click and add your details.</p>
                        </div>
                    </div><!--/.col-md-4-->
                </div><!--/.row-->
            </div><!--/.box-->
        </div><!--/.container-->
    </section><!--/#services-->

app/views/static_pages/uc.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Free coming soon template with jQuery countdown">
    <meta name="author" content="http://bootstraptaste.com">

    <title>Webuild - Free Bootstrap coming soon template with countdown</title>

    <!-- Bootstrap -->
    <link href="/assets/bootstrap.css" rel="stylesheet">
  <link href="/assets/bootstrap-theme.css" rel="stylesheet">

    <!-- siimple style -->
    <link href="/assets/cons.css" rel="stylesheet">
    
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/r/assets/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

  <div id="wrapper">
    <div class="container">
      <div class="row">
        <div class="col-sm-12 col-md-12 col-lg-12">
          <h1>Taponomics</h1>
          <h2 class="subtitle">Just give us sometime...We promise to make it awesome</h2>
          <h4 class="subtitle">Your's Truly</h4>
          <STRONG><h5 class="subtitle">Taponomics</h5></STRONG>
          <div id="countdown"></div>
          <form class="form-inline signup" role="form">
            <div class="form-group">
              <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Enter your email address">
            </div>
            <button type="submit" class="btn btn-theme">Get notified!</button>
          </form>   
          
        </div>
        
      </div>
      <div class="row">
        <div class="col-lg-6 col-lg-offset-3">
            <p class="copyright">Copyright &copy; 2016. Al rights reserved. <a href="https://www.facebook.com/Taponomics-437282369676367/?fref=ts/">Taponomics</a></p>
                        <!-- 
                            All links in the footer should remain intact. 
                            Licenseing information is available at: http://bootstraptaste.com/license/
                            You can buy this theme without footer links online at: http://bootstraptaste.com/buy/?theme=WeBuild
                        -->
        </div>
      </div>    
    </div>
  </div>
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="/assets/bootstrap.min.js"></script>
  <script src="/assets/jquery.countdown.min.js"></script>
  <script type="text/javascript">
  $('#countdown').countdown('2016/03/14', function(event) {
    $(this).html(event.strftime('%w weeks %d days <br /> %H:%M:%S'));
  });
</script>
  </body>
</html>