config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :forums
  resources :galleries
  devise_for :users
  get 'static_pages/homepage'

  get 'static_pages/dashboard'
  get 'static_pages/uc'

  resources :clubs do
    get '/clubs/:id', to: 'clubs#show'
  end
  resources :products
  resources :events

    root 'static_pages#uc'

end

app/models/forum.rb
class Forum < ActiveRecord::Base
	belongs_to :user
end

app/controllers/forums_controller.rb
class ForumsController < InheritedResources::Base

  private

    def forum_params
      params.require(:forum).permit(:question, :answer)
    end
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/views/forums/_form.html.erb
<div class="row vertical-offset-100">
      <div class="col-md-4 col-md-offset-4">
<div class="row">
  <div class="span4">
  <%= simple_form_for @forum, html: {multipart: true } do |f| %>

    <fieldset>
      <h1 class="text-center login-title"><strong> Hey Buddy!</strong> </h1>
      <p class="text-center login-title"><STRONG>Tell us what's the matter</STRONG></p>
      <%= f.input :question, placeholder: "Tell us your problem, we promise we will help", :label => 'Add Your Problem' %>
      <%= f.input :answer, :as => :hidden %>
          <div><%= f.button :submit, "Don't worry! Leave it on us", class: "btn btn-lg btn-info btn-block" %></div>
      <% end %>


    

app/views/forums/edit.html.erb
<h1>Editing Forum</h1>

<%= render 'form' %>

<%= link_to 'Show', @forum %> |
<%= link_to 'Back', forums_path %>

app/views/forums/index.html.erb
<head>
    <link href="/assets/bootstrap.min.css" rel="stylesheet">
    <link href="/assets/font-awesome.min.css" rel="stylesheet">
    <link href="/assets/forums.css" rel="stylesheet">
</head>
<body>
<div class="container-fluid">
<div class="forum">
  <div class="text-center">
    <h1>All The Problems Posted In The Forum</h1>
    <button type="button" class="btn btn-info btn-sm" data-toggle="modal" data-target="#myModal">What's this?</button>
  </div>
</div>
<%= link_to "Tell Your Problem", new_forum_path, class: "btn btn-success" %>

<% @forums.each do |forum| %>
<div class="status">
  <h2><strong>Problem:</strong></h2>
  <h3><strong><%= forum.question %></strong></h3>
  <div class="text-center">
  	<span class="admin"> 
      | <%= link_to "Show Details", forum %>
  </span>
  <div class="meta">
    <%= link_to time_ago_in_words(forum.created_at) + " ago", forum %> 
  </div>
</div>
<% end %>

<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header modal-header-success">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h1><i class="fa fa-question"></i> The Taponomics forum</h1>
      </div>
      <div class="modal-body">
        <p>We all face different Mental and Physical Problems everyday in our life, some of these problems are really serious but we don't share it with anybody, and in most of the cases tensions of these problems badly effect our health.
        	This is a try by Taponomics to solve your Physical and Menatl problem.
        </p>
        <P>You can just post your problem or qustion and wait for our experts to give you a realistic solution.</P>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>
</body>

app/views/forums/new.html.erb
<%= render 'form' %>
<div class="text-center">
<%= link_to 'Back', forums_path %>
</div>

app/views/forums/show.html.erb
<div class="container-fluid">
	<div class="forum">
<p>
  <strong>Problem:</strong>
</p>
<p>
	<%= @forum.question %>
</p>
</div>
<p>
  <strong>Solution:</strong>
</p>
<p>
  <%= @forum.answer %>
</p>
<%= link_to 'Back', forums_path %>
</div>